import getMovies from './services/getMovies/reducer';
// APPEND REDUCERS HERE (content generated by plopfile, do not remove comment)

import { NAMESPACE as GET_MOVIES } from './services/getMovies/constants';
// APPEND NAMESPACES HERE (content generated by plopfile, do not remove comment)

export default {
  [GET_MOVIES]: getMovies,
  // APPEND EXPORTS HERE (content generated by plopfile, do not remove comment)
};
