import getMovies from './services/getMovies/sagas';
// APPEND SAGAS HERE (content generated by plopfile, do not remove comment)

export default [
  getMovies,
  // APPEND EXPORTS HERE (content generated by plopfile, do not remove comment)
];
